### ISSUE TITLE
record import Error

### ISSUE THREAD

**Issue by tenzone** [terraform-providers/terraform-provider-ns1#30]
### Terraform Version
terraform .11.8

### Affected Resource(s)
importing A record

this is happening with multiple records. seems like they are all "intelligent" records

### Terraform Configuration Files
```
resource "ns1_record" "example_test" {

}
```

```
terraform import ns1_record.example_test example.com/test.example.com/A
```

First attempt shows:
```
ns1_record.example_test: Importing from ID "example.com/test.example.com/A"...
ns1_record.example_test: Import complete!
  Imported ns1_record (ID: example.com/test.example.com/A)
ns1_record.example_test: Refreshing state... (ID: example.com/test.example.com/A)

Error: ns1_record.example_test (import id: example.com/test.example.com/A): 1 error(s) occurred:

* import ns1_record.example_test result: example.com/test.example.com/A: ns1_record.example_test: unexpected EOF
```

second attempt shows a panic : 
```
ns1_record.example_test: Importing from ID "example.com/test.example.com/A"...
ns1_record.example_test: Import complete!
  Imported ns1_record (ID: example.com/test.example.com/A)
ns1_record.example_test: Refreshing state... (ID: example.com/test.example.com/A)

Error: ns1_record.example_test (import id: example.com/test.example.com/A): 1 error(s) occurred:

* import ns1_record.example_test result: example.com/test.example.com/A: ns1_record.example_test: unexpected EOF


panic: expected v to be convertible to a string, got: map[feed:581bb95a1c37270001ca2277], map[string]interface {}
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4:
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: goroutine 16 [running]:
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: github.com/terraform-providers/terraform-provider-ns1/vendor/gopkg.in/ns1/ns1-go.v2/rest/model/data.FormatInterface(0x1682000, 0xc4205d6870, 0x194, 0x1682000)
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-ns1/vendor/gopkg.in/ns1/ns1-go.v2/rest/model/data/meta.go:186 +0x66b
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: github.com/terraform-providers/terraform-provider-ns1/vendor/gopkg.in/ns1/ns1-go.v2/rest/model/data.(*Meta).StringMap(0xc42061e000, 0x2)
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-ns1/vendor/gopkg.in/ns1/ns1-go.v2/rest/model/data/meta.go:155 +0x2da
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: github.com/terraform-providers/terraform-provider-ns1/ns1.answerToMap(0xc42061e000, 0xc420146700, 0x1, 0x4, 0x0, 0x0, 0xc4204a9c90)
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-ns1/ns1/resource_record.go:246 +0x200
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: github.com/terraform-providers/terraform-provider-ns1/ns1.recordToResourceData(0xc4202af260, 0xc420177900, 0x9, 0xc420017810)
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-ns1/ns1/resource_record.go:213 +0xa07
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: github.com/terraform-providers/terraform-provider-ns1/ns1.RecordRead(0xc4202af260, 0x169ee00, 0xc420177860, 0x0, 0x1b88540)
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-ns1/ns1/resource_record.go:379 +0x1b3
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: github.com/terraform-providers/terraform-provider-ns1/vendor/github.com/hashicorp/terraform/helper/schema.(*Resource).Refresh(0xc420066e40, 0xc420150a00, 0x169ee00, 0xc420177860, 0xc4201db5b0, 0xc4202bd401, 0x80000000018)
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-ns1/vendor/github.com/hashicorp/terraform/helper/schema/resource.go:321 +0x199
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: github.com/terraform-providers/terraform-provider-ns1/vendor/github.com/hashicorp/terraform/helper/schema.(*Provider).Refresh(0xc4202ae4d0, 0xc4201509b0, 0xc420150a00, 0x1cf3000, 0x0, 0x18)
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-ns1/vendor/github.com/hashicorp/terraform/helper/schema/provider.go:284 +0x9a
2018-05-16T17:07:40.445-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: github.com/terraform-providers/terraform-provider-ns1/vendor/github.com/hashicorp/terraform/plugin.(*ResourceProviderServer).Refresh(0xc42000b3a0, 0xc4202fe0f0, 0xc4202fe2b0, 0x0, 0x0)
2018-05-16T17:07:40.446-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: 	/opt/teamcity-agent/work/222ea50a1b4f75f4/src/github.com/terraform-providers/terraform-provider-ns1/vendor/github.com/hashicorp/terraform/plugin/resource_provider.go:510 +0x4e
2018-05-16T17:07:40.446-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: reflect.Value.call(0xc420067a40, 0xc42000c5f0, 0x13, 0x1745793, 0x4, 0xc42027ff20, 0x3, 0x3, 0x0, 0x0, ...)
2018-05-16T17:07:40.446-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: 	/usr/local/go/src/reflect/value.go:434 +0x905
2018-05-16T17:07:40.446-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: reflect.Value.Call(0xc420067a40, 0xc42000c5f0, 0x13, 0xc42026af20, 0x3, 0x3, 0x0, 0x0, 0x0)
2018-05-16T17:07:40.446-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: 	/usr/local/go/src/reflect/value.go:302 +0xa4
2018-05-16T17:07:40.446-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: net/rpc.(*service).call(0xc42004f8c0, 0xc4201508c0, 0xc420017520, 0xc42014ea80, 0xc42000bf20, 0x1623660, 0xc4202fe0f0, 0x16, 0x16236a0, 0xc4202fe2b0, ...)
2018-05-16T17:07:40.446-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: 	/usr/local/go/src/net/rpc/server.go:381 +0x142
2018-05-16T17:07:40.446-0400 [DEBUG] plugin.terraform-provider-ns1_v1.0.0_x4: created by net/rpc.(*Server).ServeCodec
```
### Expected Behavior
record imported

### Actual Behavior
errors above

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform import`

**Comment by pcatalini** [comment]
Hi @tenzone, thank you for reporting this.
We already added this to our backlog.

**Comment by eravin-ns1** [comment]
We believe this was fixed in PR #133 . If you are still experiencing the issue please open a new report.
